# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "chordy"
  s.version = "0.6.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Akhil Wali"]
  s.date = "2012-10-16"
  s.description = "Chordy is a DSL written in Ruby to print guitar chords diagrams"
  s.email = "akhil.wali.10@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.rdoc",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.rdoc",
    "README.rdoc",
    "Rakefile",
    "chordy.gemspec",
    "lib/a_chords.rb",
    "lib/a_sharp_chords.rb",
    "lib/b_chords.rb",
    "lib/c_chords.rb",
    "lib/c_sharp_chords.rb",
    "lib/chord.rb",
    "lib/chordy.rb",
    "lib/chordy_script.rb",
    "lib/d_chords.rb",
    "lib/d_sharp_chords.rb",
    "lib/e_chords.rb",
    "lib/f_chords.rb",
    "lib/f_sharp_chords.rb",
    "lib/g_chords.rb",
    "lib/g_sharp_chords.rb",
    "lib/section.rb",
    "lib/text.rb",
    "lib/tuning.rb",
    "test/helper.rb",
    "test/test_chordy.rb"
  ]
  s.homepage = "http://github.com/darth10/chordy"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubyforge_project = "chordy"
  s.rubygems_version = "1.8.15"
  s.summary = "DSL for guitar chords"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0.9.2"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0.9.2"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0.9.2"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
  end
end

